getappmap/appmap-ruby

.gitignore
CHANGELOG.md
exe/appmap
lib/appmap/rspec.rb
lib/appmap/version.rb
test/fixtures/rspec_recorder/Gemfile
test/fixtures/rspec_recorder/appmap.yml
test/fixtures/rspec_recorder/lib/hello.rb
test/fixtures/rspec_recorder/spec/hello_spec.rb
test/rspec_test.rb

appmap/rspec automatically records appmaps from RSpec tests

RSpec recorder

---

CHANGELOG.md
exe/appmap
lib/appmap/command/upload.rb
lib/appmap/version.rb

* **appmap upload** expects arguments `user` and `org`.
* **appmap upload** receives and retransmits the scenario batch id assigned by the server.

Scenario batch

---

lib/appmap/rspec.rb
lib/appmap/trace/tracer.rb
lib/appmap/version.rb

Fixes for various appmap issues. See the comments on the commits for details.

Fix various appmap issues

---

.travis.yml
README.md
Rakefile
spec/abstract_controller4_base_spec.rb
spec/abstract_controller_base_spec.rb
spec/fixtures/rails_users_app/create_app
spec/rails_spec_helper.rb
spec/railtie_spec.rb
spec/record_sql_rails4_pg_spec.rb
spec/record_sql_rails_pg_spec.rb
spec/rspec_feature_metadata_spec.rb

These changes add a build config for Travis, and make builds a little less noisy.

Run tests on Travis

---

CHANGELOG.md
appmap.gemspec
lib/appmap.rb
lib/appmap/open.rb
lib/appmap/version.rb
spec/open_spec.rb

`AppMap.open` opens a scenario in the browser.

AppMap.open

---

README.md

Updated the ReadMe content regarding minitest.

Readme update minitest

---

.rubocop.yml
.travis.yml
CHANGELOG.md
lib/appmap/rails/request_handler.rb
lib/appmap/version.rb
spec/abstract_controller_base_spec.rb
spec/fixtures/rails5_users_app/app/controllers/users_controller.rb
spec/fixtures/rails5_users_app/config/routes.rb
spec/fixtures/rails5_users_app/spec/controllers/users_controller_spec.rb
spec/fixtures/rails6_users_app/app/controllers/users_controller.rb
spec/fixtures/rails6_users_app/config/routes.rb
spec/fixtures/rails6_users_app/spec/controllers/users_controller_spec.rb
spec/rails_spec_helper.rb

Recognize and record `normalized_path_info` in Rails applications, per 1.4 AppMap format version.
Also some test code refactoring. Best review commit-by-commit.

Add normalized path info in rails

---

README.md

Supported versions section added to the About chapter in README.md

Supported versions section added to About

---

README.md
lib/appmap/railtie.rb
spec/fixtures/rails5_users_app/Gemfile
spec/fixtures/rails5_users_app/config/application.rb
spec/fixtures/rails6_users_app/Gemfile
spec/fixtures/rails6_users_app/config/application.rb

* Require appmap in development and test
* Conditionally require the railtie
* Update the install instructions

Update railtie configuration

---

CHANGELOG.md
lib/appmap/rails/request_handler.rb
lib/appmap/version.rb

This fixes normalized path info in some complex projects, for example Solidus.

Correctly recognize normalized paths inside rails engines

---

lib/appmap/hook.rb

With classes enhanced by ActiveRecord, the logic to determine which code blocks to hook was missing some of the methods.

fix: Correct the method-hooking logic to capture some missing model methods

---

lib/appmap/hook.rb

This fixes an infinite loop and hang in which trace_end was called repeatedly with the same location.

fix: Only allow trace_end once per location

---

.travis.yml
README.md
Rakefile
lib/appmap/command/agent_setup/init.rb
lib/appmap/config.rb
lib/appmap/cucumber.rb
lib/appmap/depends/util.rb
lib/appmap/minitest.rb
lib/appmap/rspec.rb
lib/appmap/service/validator/config_validator.rb
lib/appmap/swagger/rake_tasks.rb
lib/appmap/util.rb
lib/appmap/version.rb
spec/depends/api_spec.rb
spec/fixtures/rails6_users_app/Gemfile
spec/fixtures/rails6_users_app/docker-compose.yml
spec/hook_spec.rb
spec/rails_recording_spec.rb
spec/railtie_spec.rb
spec/record_sql_rails_pg_spec.rb
spec/remote_recording_spec.rb
spec/spec_helper.rb

Ruby 2.5 is no longer supported by the dev team.

feat: Add support for Ruby 3.0, and drop Ruby 2.5

---

lib/appmap/gem_hooks/activejob-cancel.yml
lib/appmap/gem_hooks/activejob.yml
lib/appmap/gem_hooks/resque.yml
lib/appmap/gem_hooks/sidekiq.yml

Add labels for delayed job control in ActiveJob, Sidekiq and Resque.

feat: Add labels for job creation and canceling

---

lib/appmap/hook.rb
spec/fixtures/hook/protected_method.rb
spec/hook_spec.rb

`protected` methods are hooked, along with `public` methods.

feat: Hook protected methods

---

lib/appmap/handler/function.rb
lib/appmap/handler/net_http.rb
lib/appmap/handler/rails/template.rb
lib/appmap/hook.rb
lib/appmap/hook/method.rb
lib/appmap/hook/method/ruby2.rb
lib/appmap/hook/method/ruby3.rb
spec/hook_spec.rb

This is refactoring work ahead of a fix for #228.

Hook refactor

---

.travis.yml
lib/appmap/version.rb
spec/handler/eval_spec.rb
spec/rails_spec_helper.rb

Refactor code to be compatible with 2.5.

test: Support ruby 2.5

---

README.md
lib/appmap/middleware/remote_recording.rb
lib/appmap/trace.rb
spec/rails_spec_helper.rb
spec/remote_recording_spec.rb
spec/request_recording_spec.rb

https://www.loom.com/share/8a70b15f22c8496a9e61673afbb7055d

feat: Write an AppMap for each observed HTTP request

---

lib/appmap/gem_hooks/jwt.yml

For use with https://github.com/applandinc/appmap-js/pull/703

feat: Add builtin labels for JWT

---

lib/appmap/class_map.rb
spec/class_map_spec.rb
spec/hook_spec.rb

Fixes https://github.com/applandinc/board/issues/145

perf: Don't save comment and source in classmap.

---

lib/appmap/middleware/remote_recording.rb

Don't print an AppMap for a request that doesn't result in an http_server_request and http_server_response.

fix: Unyield static asset requests

---

lib/appmap/event.rb
lib/appmap/value_inspector.rb
lib/appmap/version.rb
spec/schema_spec.rb

https://github.com/getappmap/appmap-js/pull/864
https://github.com/getappmap/appmap/pull/34

feat: Emit nested return_value.properties

---

.travis.yml

Change deploy condition so it deploys with any Ruby 3.0.x version.

ci: Fix deploy step

---

lib/appmap/minitest.rb
lib/appmap/rspec.rb
lib/appmap/util.rb
lib/appmap/version.rb
test/fixtures/rspec_recorder/spec/failed_spec.rb
test/minitest_test.rb
test/rspec_test.rb
test/util_test.rb

Per AppMap specification 1.12.0
https://github.com/getappmap/appmap/pull/39

feat: Report metadata.test_failure

---

.travis.yml

Travis wasn't able to install PG 13 any more, updated to PG 14.

ci: bump to Postgres 14

---

.travis.yml
ext/appmap/appmap.c
lib/appmap/version.rb

Try adding 3.3.1 to the test matrix

feat: Ruby 3.3.1
