- exe/appmap
This allows users to leverage shell expansion such as filename globbing to
easily load multiple files at once.
For example:
```
$ appmap upload ~/tmp/appmap/rspec/*
Full classMap contains 39 classes
Pruned classMap contains 8 classes
Uploaded new scenario: ddf307a0-d0b2-47ea-bc37-14a1198a1973
Full classMap contains 39 classes
Pruned classMap contains 8 classes
Uploaded new scenario: ca716315-36f1-48f9-b9a9-df2d7f208ad0
Full classMap contains 39 classes
Pruned classMap contains 8 classes
Uploaded new scenario: fcbc27d7-c73d-43c7-b5ce-dc19932fd7dc
```
> Allows upload to receive multiple file names

- CHANGELOG.md
- exe/appmap
- lib/appmap/command/record.rb
- lib/appmap/rspec.rb
- lib/appmap/version.rb
Added a `detect_metadata` function which will automatically add `language` and `frameworks` to the scenario metadata.
Any code which is writing a scenario should call `detect_metadata` to get the base metadata, then add any other specific metadata (e.g. additional frameworks).
> Add language and frameworks to AppMap metadata

- CHANGELOG.md
- lib/appmap/version.rb
- public/appmap.css
Moving the record button to the bottom of the window so that users can scroll away from it and it doesn't cover branding and search by default.
> Record button position

- CHANGELOG.md
- appmap.gemspec
- lib/appmap/command/record.rb
- lib/appmap/middleware/remote_recording.rb
- lib/appmap/rspec.rb
- lib/appmap/trace/tracer.rb
- lib/appmap/version.rb
- test/fixtures/rspec_recorder/spec/decorated_hello_spec.rb
- test/fixtures/rspec_recorder/spec/labeled_hello_spec.rb
- test/fixtures/rspec_recorder/spec/plain_hello_spec.rb
- test/rspec_test.rb
Scenario metadata has `recorder` and `client` fields, to indicate how the data was collected.
Also a couple of bug fixes:
* Handle errors which occur while calling `tp.self.method(tp.method_id).parameters`
* Collect all RSpec `label` tags from the example and its parent example groups
* Improve the test coverage for inference of feature group and feature names in when recording RSpecs.
> Scenario metadata "recorder" and "client" fields

- CHANGELOG.md
- exe/appmap
- lib/appmap/command/inspect.rb
- lib/appmap/command/upload.rb
- lib/appmap/rspec.rb
- lib/appmap/version.rb
- test/cli_test.rb
- test/rspec_test.rb
RSpec recorder generates an "inventory" (AppMap with classMap, without events) named Inventory.appmap.json
appmap inspect generates an inventory AppMap which includes version, metadata, and classMap. Previously, the file output by this command was the class map represented as an array.
> Include an inventory file in appmap/rspec output

- CHANGELOG.md
- lib/appmap/middleware/remote_recording.rb
- lib/appmap/version.rb
- spec/fixtures/rails_users_app/docker-compose.yml
- spec/remote_recording_spec.rb
`DELETE` was previously failing to return scenario data. Status codes are now descriptive as intended. Content-Type headers now accurately reflect their content as intended.
> Update and fix remote recording routes

- CHANGELOG.md
- lib/appmap/event.rb
- lib/appmap/hook.rb
- lib/appmap/version.rb
- spec/hook_spec.rb
- spec/spec_helper.rb
- test/cli_test.rb
* Exceptions will be re-thrown back to the hooked application
* Add safety around indexing potentially nil backtrace locations
> Exception handling bug fixes

- .gitignore
- CHANGELOG.md
- lib/appmap/rspec.rb
- lib/appmap/version.rb
- test/fixtures/rspec_recorder/Gemfile
- test/fixtures/rspec_recorder/spec/decorated_hello_spec.rb
- test/rspec_test.rb
Ensure that `rspec` only shows up once in `metadata[:frameworks]`.
Also, make sure that the fixture's Gemfile references the local repository for testing.
> Fix frameworks metadata

- CHANGELOG.md
- lib/appmap.rb
- lib/appmap/class_map.rb
- lib/appmap/config.rb
- lib/appmap/hook.rb
- lib/appmap/trace.rb
- lib/appmap/version.rb
- spec/config_spec.rb
- spec/fixtures/hook/compare.rb
- spec/fixtures/hook/openssl_sign.rb
- spec/hook_spec.rb
- spec/util_spec.rb
There are some methods we'd always like to hook when they're loaded.
These changes add support for that, and add use it to hook
`ActiveSupport::SecurityUtils.secure_compare`.
Also, did a little refactoring, and tagged some specs with
`docker:false` to make them easier to run separately.
> Add ability to hook a method by default, label it

- CHANGELOG.md
- appmap.gemspec
- lib/appmap/cucumber.rb
- lib/appmap/hook/method.rb
- lib/appmap/version.rb
- spec/fixtures/hook/instance_method.rb
- spec/hook_spec.rb
Ensure that capturing events doesn't change the behavior of a hooked
method that uses `Time.now`. For example, if a test expects that
`Time.now` will be called a certain number of times by a hooked method,
that expectation will now be met.
> Don't interfere with methods that use Time.now

- .gitignore
- .rbenv-gemsets
- CHANGELOG.md
- README.md
- Rakefile
- appmap.gemspec
- ext/appmap/appmap.c
- ext/appmap/extconf.rb
- lib/appmap.rb
- lib/appmap/hook.rb
- lib/appmap/hook/method.rb
- lib/appmap/version.rb
- spec/fixtures/hook/singleton_method.rb
- spec/hook_spec.rb
Add a native extension that allows `qualify_method_name` to avoid any
functions the code being recorded may have redefined (e.g. `#to_s` or
`.name).
> Add extension to fix Hook.qualify_method_name

- CHANGELOG.md
- appmap.gemspec
- ext/appmap/appmap.c
- lib/appmap/util.rb
- lib/appmap/version.rb
- spec/hook_spec.rb
When getting the class of a singleton method's owner, make sure the
object returned by `__attached__.class` is actually a Module or a Class.
If it is, we can get it's name. If it's not, just call `#to_s` on the
owner's class.
Fixes #74
> Don't assume `__attached__.class` is a Module or Class

- CHANGELOG.md
- lib/appmap/rails/sql_handler.rb
- lib/appmap/version.rb
`ActiveRecord::Base.connection.server_version` was added in Rails 6.
Don't try to call it unless it's available.
> Fix problem getting database version

- CHANGELOG.md
- ext/appmap/appmap.c
- lib/appmap/hook.rb
- lib/appmap/hook/method.rb
- lib/appmap/util.rb
- lib/appmap/version.rb
- spec/hook_spec.rb
When hooking a method, we need to create a Proc that accepts the same
arguments as the original method. The only way to do this is with a
splat, i.e. `Proc.new do |*args|...`. Unfortunately, the arity of this
Proc is -1 (because it accepts a variable number of arguments), which
may or may not match the original method.
As far as I was able to determine, Ruby doesn't provide a way to get the
signature of a method and define a Proc with a matching signature. The
closest I came was to consider parsing the array returned from
`#parameters` and reconstructing the original signature. This isn't a
viable approach, because there's no way to obtain the default value for
an optional parameter.
So, instead, when hooking a method, cache its arity in the class that
owns it, and reimplement `#arity` so …
> Ensure that hooking preserves method arity

- CHANGELOG.md
- lib/appmap/rails/sql_handler.rb
- lib/appmap/version.rb
Only warn once about problems determining database version for an
ActiveRecord connection.
> Get rid of extra warnings

- CHANGELOG.md
- lib/appmap/event.rb
- lib/appmap/version.rb
- spec/fixtures/hook/exception_method.rb
- spec/hook_spec.rb
Make sure `MethodEvent#display_string` can handle values with
problematic `#to_s` and `#inspect` methods.
> Fix `MethodEvent#display_string`

- CHANGELOG.md
- README.md
- Rakefile
- appmap.yml
- lib/appmap/class_map.rb
- lib/appmap/config.rb
- lib/appmap/version.rb
- spec/hook_spec.rb
- test/fixtures/gem_test/Gemfile
- test/fixtures/gem_test/appmap.yml
- test/fixtures/gem_test/test/to_param_test.rb
- test/gem_test.rb
- test/minitest_test.rb
- test/openssl_test.rb
Enable appmap.yml to specify a `gem` name to map the gem.
Example:
```
name: gem_test
packages:
- gem: activesupport
```
> Specify a gem name to record in appmap.yml

- .gitignore
- .rubocop.yml
- CHANGELOG.md
- Rakefile
- appmap.gemspec
- lib/appmap.rb
- lib/appmap/class_map.rb
- lib/appmap/rspec.rb
- lib/appmap/version.rb
- spec/class_map_spec.rb
- spec/hook_spec.rb
- test/expectations/openssl_test_key_sign1.json
- test/expectations/openssl_test_key_sign2.json
- test/openssl_test.rb
This change builds on https://github.com/applandinc/appmap/pull/9 to capture method source code and documentation comments in the classmap. Note for RSpec runs to avoid duplication code is only recorded in the inventory file.
> Capture method source code and comment

- .rubocop.yml
- CHANGELOG.md
- lib/appmap/event.rb
- lib/appmap/version.rb
- spec/fixtures/hook/instance_method.rb
- spec/hook_spec.rb
This change makes argument handling a bit smarter, to correctly extract keyword and rest arguments.
Thanks to @flywithmemsl for inspiration. See https://github.com/applandinc/appmap-ruby/pull/85 for the original implementation.
> Fix parameter mapping with keyword and rest arguments

- CHANGELOG.md
- README.md
- lib/appmap/config.rb
- lib/appmap/hook/method.rb
- lib/appmap/trace.rb
- lib/appmap/version.rb
- spec/abstract_controller_base_spec.rb
- spec/fixtures/rails5_users_app/Gemfile
- spec/fixtures/rails5_users_app/appmap.yml
- spec/fixtures/rails5_users_app/spec/controllers/users_controller_api_spec.rb
- spec/fixtures/rails5_users_app/spec/controllers/users_controller_spec.rb
- spec/fixtures/rails6_users_app/Gemfile
- spec/fixtures/rails6_users_app/appmap.yml
- spec/fixtures/rails6_users_app/spec/controllers/users_controller_api_spec.rb
- spec/fixtures/rails6_users_app/spec/controllers/users_controller_spec.rb
- spec/hook_spec.rb
* Implement API "surface" recording. When `shallow: true`, only the first function call entering a package is recorded. Subsequent functions within the package are not recorded. When recording gems using the `gem: <gem_name>` option in appmap.yml, shallow recording is the default.
* Record `ActionView::Renderer#render` automatically, and apply the label `view`.
* Update the gem version to `1.0.0`.
Regarding the tests on Travis ; `appmap-ruby` is broken on Travis for some reason. I have sent a note to their support. Meanwhile, I ran the test suite locally on a clean checkout and it passed.
> Record "view" rendering, and implement API "surface" recording

- CHANGELOG.md
- README.md
- lib/appmap/class_map.rb
- lib/appmap/version.rb
- spec/fixtures/hook/labels.rb
- spec/hook_spec.rb
- spec/spec_helper.rb
The [AppMap data format](https://github.com/applandinc/appmap) provides for class and function `labels`, which can be used to enhance the AppMap visualizations, and to programatically analyze the data.
You can apply function labels using source code comments in your Ruby code. To apply a labels to a function, add a `@label` or `@labels` line to the comment which immediately precedes a function.
For example, if you add this comment to your source code:
```ruby
class ApiKey
def authenticate(key)
end
end
```
Then the AppMap metadata section for this function will include:
```json
{
"name": "authenticate",
"type": "function",
"labels": [ "provider.authentication", "security" ]
}
```
> Labels from comments

- CHANGELOG.md
- lib/appmap/config.rb
- lib/appmap/hook/method.rb
- lib/appmap/version.rb
- spec/fixtures/rails5_users_app/docker-compose.yml
- spec/fixtures/rails6_users_app/docker-compose.yml
Don't rely on `gemspec.source_paths` to list all the source locations in a gem. Hook any code that's loaded
from inside the `gem_dir`.
> Hook code anywhere in gem

- CHANGELOG.md
- README.md
- lib/appmap/event.rb
- lib/appmap/rails/request_handler.rb
- lib/appmap/version.rb
- spec/abstract_controller_base_spec.rb
- spec/fixtures/rails5_users_app/Gemfile
- spec/fixtures/rails5_users_app/app/controllers/api/users_controller.rb
- spec/fixtures/rails5_users_app/app/controllers/users_controller.rb
- spec/fixtures/rails5_users_app/config/application.rb
- spec/fixtures/rails5_users_app/create_app
- spec/fixtures/rails5_users_app/spec/controllers/users_controller_api_spec.rb
- spec/fixtures/rails5_users_app/spec/controllers/users_controller_spec.rb
- spec/fixtures/rails5_users_app/spec/rails_helper.rb
- spec/fixtures/rails6_users_app/Gemfile
- spec/fixtures/rails6_users_app/app/controllers/api/users_controller.rb
- spec/fixtures/rails6_users_app/app/controllers/users_controller.rb
- spec/fixtures/rails6_users_app/config/application.rb
- spec/fixtures/rails6_users_app/create_app
- spec/fixtures/rails6_users_app/spec/controllers/users_controller_api_spec.rb
- spec/fixtures/rails6_users_app/spec/controllers/users_controller_spec.rb
- spec/fixtures/rails6_users_app/spec/rails_helper.rb
- spec/record_sql_rails_pg_spec.rb
- spec/spec_helper.rb
Adds more useful information to `http_server_request` and `_response`. This enhances our ability to generate Swagger.
* Record `name` and `class` of each entry in Hash-like parameters, messages, and return values.
Example: 
```ruby
'name' => 'user',
'properties' => [
{ 'name' => 'login', 'class' => 'String' },
{ 'name' => 'password', 'class' => 'String' }
]
```
* Record client-sent headers in HTTP server request and response.
Example:
```ruby
'http_server_request' => hash_including(
'headers' => hash_including('X-Sandwich' => 'turkey')
)
```
* Record HTTP server request `mime_type` (client `Content-Type` header).
* Record HTTP server request `authorization` (client `Authorization` header).
Fix specs by including only `sequel` or `active_record` database cleaner.
> Enhance HTTP server request recording

- .releaserc.yml
- .travis.yml
- README_CI.md
- Rakefile
- appmap.gemspec
- release.sh
1. CI deployment step is added, bringing in `semantic-release` logic 
2. As a part of automated release process, publication to rubygems happens (alternative gem names are supported for testing purposes)
This change has impact on the `master` branch management, check semantic-release commits conventions and get prepared to Travis interventions (version increases, chore commits, github releases) 
* `GH_TOKEN`: used by `semantic-release` to push changes to Github and manage releases
* `GEM_HOST_API_KEY`: rubygems API key
* `GEM_ALTERNATIVE_NAME` (optional): used for testing of CI flows, to avoid publication of test releases under official package name
`README_CI.md`
> feat(ci): semantic-release and publication to rubygems

- .travis.yml
- README_CI.md
If `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD` are defined,
Travis performs docker login prior to running tests, in order
to avoid hitting anonymous pull quotas.
For security purposes, it's recommended to use dedicated Dockerhub account,
and access token instead of primary password.
> ci-performance: support optional Dockerhub auth

- README.md
- lib/appmap/config.rb
- lib/appmap/hook.rb
- lib/appmap/util.rb
- spec/abstract_controller_base_spec.rb
- spec/hook_spec.rb
Greatly speed up the time to instrument the Ruby code and get the processing going.
Key insight: TracePoint will notify whenever loading begins of a new class/module. The appmap-ruby Config has a master list of all the source code paths and gems that will be instrumented. So, it can skip all the hook-checking for files (entire packages, really) that it knows aren't going to be hooked.
This optimization drops the startup time for AppMapping the AppMap Server from 19.5 seconds to 4.4.
> Optimize instrumentation

- .travis.yml
(bring back the previous change after it was unintentionally deleted)
> ci-performance: support optional Dockerhub auth again

- lib/appmap/config.rb
- lib/appmap/handler/rails/template.rb
- lib/appmap/hook.rb
- spec/hook_spec.rb
> fix: Add the proper template function hooks for Rails 6.0.7

- README.md
- lib/appmap.rb
- lib/appmap/railtie.rb
- lib/appmap/version.rb
- spec/fixtures/rails5_users_app/config/application.rb
- spec/fixtures/rails6_users_app/config/application.rb
- spec/railtie_spec.rb
Initialization (code hooking) only proceeds if `APPMAP=true`.
Omitting `APPMAP=true` enables quick and clean startup, and normal debugging, even in test and development.
> Conditional init

- .dockerignore
- lib/appmap/event.rb
- lib/appmap/minitest.rb
- lib/appmap/rspec.rb
- lib/appmap/util.rb
- spec/fixtures/hook/exception_method.rb
- spec/hook_spec.rb
- test/bundle_vendor_test.rb
- test/fixtures/bundle_vendor_app/Gemfile
- test/fixtures/bundle_vendor_app/appmap.yml
- test/fixtures/bundle_vendor_app/cli.rb
- test/gem_test.rb
Ensure that gems are recorded even when they are installed to a sub-directory of the project root. 
Sanitize exception message strings to avoid JSON encoding errors.
> Fix bundle path and exception messages

- lib/appmap.rb
- lib/appmap/minitest.rb
- lib/appmap/railtie.rb
- lib/appmap/rspec.rb
- spec/fixtures/rails5_users_app/config/application.rb
- spec/fixtures/rails5_users_app/config/initializers/record_button.rb
- spec/fixtures/rails5_users_app/spec/rails_helper.rb
- spec/fixtures/rails6_users_app/config/application.rb
- spec/fixtures/rails6_users_app/config/initializers/record_button.rb
- spec/fixtures/rails6_users_app/spec/rails_helper.rb
* In the context of a Rails app, [require the railtie](https://github.com/applandinc/appmap-ruby/pull/133/files#diff-4ba50e46d8f94bb627d8aeae705c0255d212bb36dae6f5fdff4c78ee316f3f64R108).
* Railtie [configures the app for remote recording automatically](https://github.com/applandinc/appmap-ruby/pull/133/files#diff-d850506678279e89de4e85e240bc997a21f7cd006c90389e795796f3b399936bR6).
* If `minitest` gem is available in the bundle, [add appmap hooks](https://github.com/applandinc/appmap-ruby/pull/133/files#diff-4ba50e46d8f94bb627d8aeae705c0255d212bb36dae6f5fdff4c78ee316f3f64R117).
* If `RSpec` exists, [add appmap hooks](https://github.com/applandinc/appmap-ruby/pull/133/files#diff-4ba50e46d8f94bb627d8aeae705c0255d212bb36dae6f5fdff4c78ee316f3f64R112).
> feat: Automatically require railtie, minitest, and rspec helpers

- lib/appmap.rb
- lib/appmap/config.rb
- lib/appmap/util.rb
- lib/appmap/version.rb
- spec/abstract_controller_base_spec.rb
- spec/config_spec.rb
- spec/hook_spec.rb
- spec/record_net_http_spec.rb
If appmap.yml is not found, warn the user.
Detect some possible source paths, and the project name from the .git file,
and use this info to create a temporary appmap.yml.
Print it to the console so the user can use it as a starting point.
> feat: Provide default appmap.yml settings

- lib/appmap.rb
- lib/appmap/config.rb
- lib/appmap/handler/rails/template.rb
- lib/appmap/trace.rb
`if defined?(::Rails::Railtie)` doesn't reliably return true, due to load order issues. So, we also use TracePoint to watch modules being loaded.
This PR also removes redundant methods from the ClassMap, by ensuring that method objects are well-behaved in a Set.
> fix: Fix problems with auto-requiring appmap modules

- .travis.yml
- Rakefile
- appmap.gemspec
- lib/appmap/handler/net_http.rb
- lib/appmap/handler/rails/template.rb
- lib/appmap/hook.rb
- lib/appmap/hook/method.rb
- lib/appmap/trace.rb
- lib/appmap/util.rb
- spec/fixtures/hook/kwargs.rb
- spec/hook_spec.rb
- spec/record_net_http_spec.rb
There are two main elements to this fix:
* Call https://ruby-doc.org/core-2.7.0/Proc.html#method-i-ruby2_keywords
* Fix a probable side-effect of using ruby_keywords: https://github.com/applandinc/appmap-ruby/pull/154/files#diff-95a15f6e0d63580f2d31bf5a2e866f1062fbda51da73ad9089c579b952467a08R54
Fixes https://github.com/applandinc/appmap-ruby/issues/153
> fix: Workaround Ruby bug in 2.7.3 with kwrest

- lib/appmap.rb
require 'appmap/railtie' will trigger autoload of 'rails/railtie', which
will allow AppMap::Railtie to work properly.
require 'appmap/railtie' when the class Rails::Railtie is first observed
does not work, because other classes such as
Rails::Railtie::Configuration are not yet available.
So, check if Rails is defined. If so, load 'appmap/railtie'. In a Rails
app, Rails is always defined when the dependency gems are loaded,
because Rails startup begins by loading 'rails/commands'.
> fix: Require appmap/railtie if Rails is defined

- lib/appmap/command/agent_setup/status.rb
- lib/appmap/service/integration_test_path_finder.rb
- lib/appmap/service/test_command_provider.rb
- lib/appmap/service/test_framework_detector.rb
- spec/fixtures/rails6_users_app/test/controllers/functional_calc_test.rb
- spec/fixtures/rails6_users_app/test/integration/integration_calc_test.rb
- test/agent_setup_status_test.rb
Example output for `rails6_users_app`:
```json
{
"test_commands": [
{
"framework": "rspec",
"command": "APPMAP=true bundle exec rspec spec/controllers"
},
{
"framework": "minitest",
"command": "APPMAP=true bundle exec rails test test/controllers test/integration"
},
{
"framework": "cucumber",
"command": "APPMAP=true bundle exec cucumber"
}
],
"properties": {
"config": {
"app": "rails6_users_app",
"present": true,
"valid": true
},
"project": {
"agentVersion": "0.57.0",
"language": "ruby",
"remoteRecordingCapable": true,
"integrationTests": true
}
}
}
```
> feat: Add `test_commands` sections to `appmap-agent-status` executable

- lib/appmap/event.rb
- lib/appmap/handler/rails/template.rb
- lib/appmap/trace.rb
An event may be partially constructed, and then completed at a later time.
When the event is only partially constructed, it's not ready for serialization to the AppMap file.
This problem manifests when a thread is continually pulling
and serializing events. For example, during remote recording.
> fix: Events may be constructed in stages

- config-schema.yml
Based on: https://appland.com/docs/reference/appmap-python.html#configuration
I wrote it in yaml for readability.
To quickly check it out:
* Convert to json: https://onlineyamltools.com/convert-yaml-to-json
* Try it out: https://onlineyamltools.com/convert-yaml-to-json
> feat: add JSON schema (in yaml for readability)

- lib/appmap/event.rb
- lib/appmap/util.rb
Unless a Rails environment is assured, don't use 'try'.
Add a simplified, equivalent method to AppMap::Util.
> fix: Remove improper reliance on Rails 'try'

- lib/appmap/command/agent_setup/status.rb
- lib/appmap/service/integration_test_path_finder.rb
- lib/appmap/service/test_command_provider.rb
- spec/service/integration_test_path_finder_spec.rb
@ptrdvrk found an app where tests are located in `test/internal/app/controllers`. We can easily include children dirs into the list of possible paths.
> feat: Include children `controllers` and `integration` folders into minitest paths

- CHANGELOG.md
- lib/appmap/version.rb
node_modules is missing from 0.62.0. This gem version will be published manually while we troubleshoot.
> Update version and changelog for 0.62.1

- Rakefile
- release.sh
semantic-release runs 'gem build appmap.gemspec', not 'rake gem:build',
so the customization that was running yarn install --prod during the
rake task wasn't actually getting called when releases were made.
The result was missing node_modules, and the rake tasks that depend on
the NodeJS code were broken.
> fix: Run yarn install --prod in ./release.sh

- lib/appmap/service/validator/config_validator.rb
- test/agent_setup_validate_test.rb
Interpolate the config file name in the validation messages. This allows
them to be displayed directly to the user, without requiring any
additional processing.
> feat: Show config file name in validation messages

- lib/appmap/config.rb
- lib/appmap/hook.rb
- lib/appmap/util.rb
- spec/config_spec.rb
- spec/fixtures/depends/revoke_api_key.appmap.json
- spec/fixtures/depends/user_page_scenario.appmap.json
- spec/fixtures/rails5_users_app/appmap.yml
- spec/fixtures/rails6_users_app/appmap.yml
- spec/rails_recording_spec.rb
Add a config line in the functions section such as this:
```
- name: logger/Logger#add
builtin: true
label: log
```
Note that the 'name' syntax  with the fully-qualified function name is
also a new addition in this commit.
> feat: Builtin code such as Ruby Logger can be hooked via appmap.yml

- ext/appmap/extconf.rb
Xcode 13* introduces a new warning named compound-token-split-by-macro.
One of the ruby headers triggers this warning. We build our extension
with -Werror in CFLAGS, resulting in the issue described here:
https://bugs.ruby-lang.org/issues/17865 .
This doesn't appear to be a bug in the ruby header, so it seems safe to
ignore it until it's fixed. This change keeps -Werror in CFLAGS, and
just disables compound-token-split-by-macro.
* The issue indicates this behavior was actually introduced in clang 12, which
was probably part of Xcode 12.
> fix: Fix compilation on macOS with Xcode 13

- lib/appmap/command/inspect.rb
- spec/depends/api_spec.rb
Pass the correct directory to --appmap-dir when running the Depends API
smoke test.
Using the incorrect directory causes a Promise rejection, which results this warning in Node 14:
```
stderr: Fingerprinting appmaps in /Users/ajp/src/applandinc/appmap-ruby/spec/fixtures/depends/spec/fixtures/depends
stderr: Scanning /Users/ajp/src/applandinc/appmap-ruby/spec/fixtures/depends/spec/fixtures/depends for AppMaps
stderr: (node:41934) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Users/ajp/src/applandinc/appmap-ruby/spec/fixtures/depends/spec/fixtures/depends'
stderr:     at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
stderr:     at processPromiseRejections (internal/process/promises.js:247:11)
stderr:     at …
```
> test: Fix argument for Depends API smoke test

- lib/appmap/builtin_hooks/json.yml
- lib/appmap/builtin_hooks/net/http.yml
- lib/appmap/builtin_hooks/openssl.yml
- lib/appmap/builtin_hooks/yaml.yml
- lib/appmap/config.rb
- lib/appmap/event.rb
- lib/appmap/gem_hooks/actionpack.yml
- lib/appmap/gem_hooks/actionview.yml
- lib/appmap/gem_hooks/activesupport.yml
- lib/appmap/gem_hooks/cancancan.yml
- lib/appmap/hook.rb
- lib/appmap/util.rb
- spec/config_spec.rb
Hooks that are builtin to appmap-ruby are now all moved to YAML files in `lib/appmap/builtin_hooks` and `lib/appmap/gem_hooks`. So, builtin Ruby library and gem hooks, with labels, can now be added without writing Ruby code.
Example: https://github.com/applandinc/appmap-ruby/pull/202/files#diff-6d12bf13835e3e35920437bd8ff7f9526d256b39ab1b31c3897141e9d8b5ec31R1
```yaml
- method: OpenSSL::PKey::PKey#sign
label: crypto.pkey
- methods:
- OpenSSL::X509::Request#sign
- OpenSSL::X509::Request#verify
label: crypto.x509
```
`builtin_hooks` is for anything that's part of Ruby itself. The reason builtins are treated differently than gems is that there's no Gem path available from bundler. `gem_hooks` is for Gems. Perhaps this distinction could be removed, but I didn't want to bite that off in this …
> feat: Externalize hooks config

- lib/appmap/util.rb
- spec/config_spec.rb
Because we're propagating the return value of `Logger#info`, [a warning message](https://github.com/applandinc/appmap-ruby/blob/master/lib/appmap/config.rb#L69) causes [`Config::Package.build_from_gem`](https://github.com/applandinc/appmap-ruby/blob/master/lib/appmap/config.rb#L60) to return `true`, causing [`Config::TargetMethods.package_hooks`](https://github.com/applandinc/appmap-ruby/blob/master/lib/appmap/config.rb#L148) to continue processing hooks on an invalid type (`TrueClass` instead of `Config::Package`).
I'd considered making a type check here as well, but opted to leave it as is.
https://github.com/applandinc/appmap-ruby/blob/master/lib/appmap/config.rb#L157
> fix: Missing gems will no longer attempt to be hooked

- lib/appmap/class_map.rb
- lib/appmap/config.rb
- spec/class_map_spec.rb
- spec/fixtures/hook/pkg_a/a.rb
- spec/fixtures/hook/sub_packages.rb
- spec/hook_spec.rb
- spec/rails_recording_spec.rb
When a recorded path has recorded sub-folders, appmap-ruby will produce a class map with nested `package` elements.
> feat: Report sub-packages in the class map

- ext/appmap/extconf.rb
- lib/appmap/hook/method.rb
This changes target a problem we've seen calling a method that takes a Hash followed by a keyword argument. One way this could happen is if an instance of `Proc` doesn't respond to `#ruby2_keywords`, so log a warning if this is is the case.
> ci: Test ruby 3.1

- lib/appmap/util.rb
- spec/rails_recording_spec.rb
Rack doesn’t prepend HTTP_ to the content type header, so we are usually/always missing it on requests.
> fix: Ensure Content-Type is included in request headers

- .travis.yml
- Rakefile
- appmap.gemspec
- lib/appmap/command/index.rb
- lib/appmap/command/inspect.rb
- lib/appmap/node_cli.rb
- package.json
- release.sh
- spec/fixtures/rails6_users_app/Dockerfile
- spec/fixtures/rails6_users_app/package.json
- spec/fixtures/rails6_users_app/yarn.lock
- spec/swagger/swagger_spec.rb
You might be familiar with how the appmap-ruby `swagger` Rake tasks used a bundled copy of appmap-js. Now that we are requiring the installation of other code from NPM, such as `@appland/scanner`, it doesn’t make sense to do this any more. It was fragile and it kept breaking. This update runs the `@appland/appmap openapi` using `npx`
The user must install `@appland/appmap` to the enclosing project.
This also applies to the `depends` task.
* Update https://appland.com/docs/reference/appmap-ruby.html#swagger-openapi-generation
> fix: No longer bundle @appland/appmap with this gem

- lib/appmap/hook/method.rb
- spec/fixtures/hook/report_parameters.rb
- spec/hook_spec.rb
Patch Object and Module to provide the proper parameters (method signature) on hooked methods.
> fix: Override method accessors to provide the correct signature

- lib/appmap/config.rb
- lib/appmap/handler.rb
- lib/appmap/hook.rb
- lib/appmap/util.rb
This makes it easier for the user to specify custom handlers.
For example, specifying
- methods:
- Acme::Request.make
handler_class: Acme::Request::AppmapHandler
in the config file will make AppMap automatically require `acme/request/appmap_handler` before setting up the hook.
> Autoload hook handlers

- .travis.yml
Get rid of the GEM_ALTERNATIVE_NAME env entry for the test stage. It's
not needed, and adds an extra build job that doesn't test any additional
functionality.
> ci: Remove GEM_ALTERNATIVE_NAME from Travis config

- lib/appmap/agent.rb
- lib/appmap/event.rb
- lib/appmap/gem_hooks/actionpack.yml
- lib/appmap/handler.rb
- lib/appmap/handler/rails/render_handler.rb
- lib/appmap/handler/rails/request_handler.rb
- lib/appmap/handler/rails/sql_handler.rb
- lib/appmap/hook/method.rb
- spec/handler/eval_spec.rb
- spec/hook_spec.rb
- spec/rails_recording_spec.rb
- test/expectations/openssl_test_key_sign2-3.1.json
Implement https://github.com/applandinc/appmap/pull/29
1) Hook template rendering so that we can grab the `:json` argument
2) Always emit the parameter schema of an HTTP server response; optionally emit it when enabled by APPMAP_PARAMETER_SCHEMA
3) Emit `size` of Array and Hash objects
4) Emit query `EXPLAIN` plan when enabled by APPMAP_EXPLAIN_QUERIES
> feat: Parameter schema, query EXPLAIN and size

- lib/appmap/event.rb
Limit invocation of #size to known-safe objects - initially, Array and
Hash.
> fix: Don't call #size on complex objects

- lib/appmap/hook/method.rb
Only show this message if `Hook::LOG` is true.
Previously, this message appeared in the Travis job. e.g. https://app.travis-ci.com/github/applandinc/appmap-ruby/jobs/569606383#L885 . Examining the build log for this PR will show that it no longer appears.
> fix: Only warn if Hook::LOG is true

- lib/appmap/hook/method/ruby2.rb
- lib/appmap/hook/method/ruby3.rb
- spec/handler/class_with_eval.rb
- spec/handler/eval_spec.rb
Eval handler relies on specific call stack layout when recovering
original eval call context. Since call hook handler used to
short-circuit over trace_call method when not tracing, the layout
was unexpected when the handlers were loaded but tracing disabled
(eg. when initial code load is performed dynamically after loading
appmap gem).
The fix is to always call trace_call and short-circuit in there,
keeping the call stack the same.
Alternative, rejected solutions:
- check for tracing being disabled in eval handler and use the
correct (shallower) call stack depth in this case,
- examine all frames sequentially in the eval handler until the
correct one is found.
Fixes #254
> fix: Eval handler now works correctly even when not tracing

- appmap.gemspec
If there are AppMaps in the gem, the VS Code extension's Install Guide sees them and thinks recordings have been made.
> fix: Exclude AppMaps from the gem when packaging

- appmap.gemspec
Fixes Windows install error:
```
Installing appmap 0.83.4 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------
Errno::EACCES: Permission denied @ rb_file_s_symlink - (../../database.yml, C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/appmap-0.83.4/spec/fixtures/rails5_users_app/config/database.yml)
C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/package.rb:447:in `symlink'
C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/package.rb:447:in `block (2 levels) in extract_tar_gz'
C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/package.rb:413:in `block in extract_tar_gz'
C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/package.rb:525:in `block in open_tar_gz' …
```
> fix: Remove spec and test from the gem

- lib/appmap/trace.rb
- spec/ruby_method_spec.rb
The `method_source` gem will happily take a source path such as
`<internal:pack>:243` and [attempt to open it as a file](https://github.com/banister/method_source/blob/master/lib/method_source.rb#L53). In this case, Windows will raise an EINVAL error which is not caught by the gem and the error will propagate through the agent and fail a pending recording.
This did not seem to affect any other platform.
> fix: Catch an uncaught EINVAL on Windows when fetching method comments

- lib/appmap/builtin_hooks/activesupport.yml
- lib/appmap/builtin_hooks/ruby.yml
- lib/appmap/event.rb
- lib/appmap/handler/eval_handler.rb
- lib/appmap/handler/marshal_load_handler.rb
- spec/handler/eval_handler_spec.rb
Parameters for `Kernel#eval` and `Marshal#load` are overridden to present the first param as the string to eval/load, rather than presenting all params as a single Array (`:rest`).
> feat: Tune method parameters

- lib/appmap/hook.rb
Doing `config.lookup_package` check first returns early in 98.7% of cases in sample_app_6th_ed.
```
APPMAP=true DISABLE_SPRING=true GEM_HOME=gems bundle exec rails test > lambda_hook.txt
$ cat lambda_hook.txt | grep 'trace_end_hook_body_3' | wc -l
5863
$ cat lambda_hook.txt | grep 'trace_end_hook_body_3.5' | wc -l
74
```
It decreased `instance_methods.each(&hook.(cls))` execution from `0.169` to `0.079`.
Addresses https://github.com/applandinc/board/issues/129
> Optimize `config.lookup_package` check in `trace_end`

- Gemfile
- appmap.gemspec
Pin Rack to version 2 for testing purposes
> fix: Make Rack a runtime dependency

- .rubocop.yml
- lib/appmap/trace.rb
AppMap needs to extract method comments to apply labels. This change makes this process faster.
Note this is roughly the same change as in #279 but (IMO) a bit cleaner, plus it avoids reading the whole file by using IO#lines iterator and only taking the required number of lines. As such it fixes #276 (in a way).
> fix: Faster comment extraction

- lib/appmap/cucumber.rb
- lib/appmap/middleware/remote_recording.rb
- lib/appmap/minitest.rb
- lib/appmap/record.rb
- lib/appmap/rspec.rb
- lib/appmap/version.rb
- test/cucumber_test.rb
- test/minitest_test.rb
- test/rspec_test.rb
Supports AppMap version 1.9.0
https://github.com/applandinc/appmap/pull/32
> feat: Emit metadata.recorder.type

- lib/appmap/handler/rails/sql_handler.rb
- spec/record_sql_rails_pg_spec.rb
It's unsafe to query the DB for the version when already inside of a hook.
I experimented with various ways of querying the DB outside of hooks, but they are all super-hacky and I don't think it's worth the effort since there is nothing downstream that depends on the `server_version` being present. This field is optional in the spec.
> fix: Drop database server version

- lib/appmap/event.rb
- lib/appmap/handler/rails/request_handler.rb
- lib/appmap/handler/rails/sql_handler.rb
- lib/appmap/hook/method.rb
- lib/appmap/hook/method/ruby2.rb
- lib/appmap/hook/method/ruby3.rb
- lib/appmap/util.rb
Record AppMap's overhead before a function call and after a function call, and save this data in the event.
Do this for:
- function calls
- sql queries
- http requests
Generating this data makes it possible to display a [report](https://github.com/applandinc/appmap-js/pull/721) of functions with the highest AppMap overhead. 
Addresses https://github.com/applandinc/board/issues/140
Before
```
npm start stats -- /home/test/src/sample_app_6th_ed --limit 200 
0000000000s DELETE /relationships/980190962 1 calls
0000000000s GET /login 3 calls
0000000000s GET /about 1 calls
0000000000s GET /contact 1 calls
0000000000s GET /help 1 calls
0000000000s GET /signup 3 calls
0000000000s DELETE /users/762146111 2 calls
0000000000s GET /users/762146111/edit 4 calls
```
After
```
0.00451700s POST /login 21 …
```
> feat: Record AppMap's overhead in `elapsed_instrumentation`

- lib/appmap/config.rb
When appmap.yml does not exist, a default file is generated. Include language and appmap_dir in this file.
> fix: Add language, appmap_dir to generated appmap.yml

- .rubocop.yml
- appmap.gemspec
- lib/appmap/detect_enabled.rb
- spec/detect_enabled_spec.rb
- test/rspec_test.rb
If we want to have recording by default, I think this makes more sense and is what user would expect: appmap is enabled by default whenever tests are run, regardless of environment variables (which might not even be set, even for example for rails — it only uses them as one input to determine environment).
It can still be disabled with `APPMAP=false` or `APPMAP_RECORD_RSPEC=false`.
Fixes #288
> Record all tests by default

- .travis.yml
- ext/appmap/appmap.c
`Init_appmap()` is an old (K&R) C signature style which is wrong and causes a warning with `-Wold-style-definition` (and an error with `-Werror`).
Note: this issue has been reported by a user (Mike State on appmap-group.slack.com) and they might be using the fix branch directly, so let's keep it around for a while longer after it's merged.
> fix: Use correct signature for Init_appmap() in appmap.c

- .rubocop.yml
- .travis.yml
- lib/appmap/command/agent_setup/validate.rb
- lib/appmap/service/config_analyzer.rb
- lib/appmap/service/validator/config_validator.rb
- lib/appmap/service/validator/violation.rb
- spec/service/config_analyzer_spec.rb
- test/agent_setup_status_test.rb
- test/agent_setup_validate_test.rb
Non-Rails projects won't autoload AppMap, but this is not a fatal
error. Instead of signaling one show a warning with some details on
how to ensure it's loaded.
Fixes #292
Note https://github.com/getappmap/appmap-js/pull/829 is needed for this to actually work.
> Allow non rails projects in validation

- lib/appmap/util.rb
- spec/util_spec.rb
[Forem](https://github.com/forem/forem) was passing to `swaggerize_path` the input
```
(/locale/:locale)/api/users/:id(.:format)
```
returning the output
```
(/locale/{locale)}/api/users/{id}
```
The`)` should have not been inside `{}`.
This pr fixes this.
> fix: Don't match ending ) in swaggerize_path

- lib/appmap/rspec.rb
- spec/fixtures/rails6_users_app/Gemfile
- spec/fixtures/rails6_users_app/spec/requests/rswag_spec.rb
- spec/fixtures/rails6_users_app/spec/swagger_helper.rb
- spec/service/integration_test_path_finder_spec.rb
- test/agent_setup_status_test.rb
When running rswag tests, pass the `RSpec::Core::Example` object to rswag's [`run_test!`](https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/example_group_helpers.rb#L118).
`RSpec::Core::Example` wasn't being passed. AppMap wasn't crashing so far because example wasn't being used with with `RSPEC_VERSION < 3`. When used with rspec version 3+ this bug started to occur.
Added testcase `spec/fixtures/rails6_users_app/spec/requests/rswag_spec.rb` and adjusted existing testcases to account for it.
After this change, verified Forem's `./spec/requests/api/v1` tests all pass without the exclusion pattern used before for `./spec/requests/api/v1/docs/*_spec.rb`
Fixes https://github.com/getappmap/appmap-ruby/issues/309
> fix: Fix bug with rswag's `run_test!`

- .travis.yml
- lib/appmap/config.rb
- lib/appmap/version.rb
- spec/fixtures/hook/anonargs_passed.rb
- spec/fixtures/hook/anonkwargs_passed.rb
- spec/fixtures/hook/args_to_kwargs.rb
- spec/fixtures/hook/proc_no_autosplat.rb
- spec/hook_spec.rb
- spec/request_recording_spec.rb
- spec/spec_helper.rb
- Add Ruby 3.2 to the test matrix on CI.
- Remove from existing tests use of `Dir.exists?` and `File.exists?` which is deprecated in Ruby 3.2.
- Add four new tests that verify the agent works with the following three changes in Ruby 3.2
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/ 
```
Anonymous rest and keyword rest arguments can now be passed as arguments, instead of
just used in method parameters. 
```
```
Methods taking a rest parameter (like *args) and wishing to delegate keyword arguments
through foo(*args) must now be marked with ruby2_keywords (if not already the case). In
other words, all methods wishing to delegate keyword arguments through *args must now
be marked with ruby2_keywords, with no exception. 
```
```
A proc that accepts a single positional …
```
> feat: Support Ruby 3.2

- lib/appmap/value_inspector.rb
- spec/schema_spec.rb
- spec/value_inspector_spec.rb
`items` must be captured for array-like data structures to describe the schema of the data held within. Previously array elements were assumed to be objects.
This means we should now be able to write proper schema for the following examples.
Given the following JSON response:
```json
[ "This", "is", "my", "array"]
```
The following properties would be made available in AppMap data:
```json
"return_value": {
"class": "Array",
"items": [ "class": "String" ]
}
```
And can be translated to an OpenAPI compliant definition:
```yml
/api/example:
get:
responses:
'200':
content:
application/json:
schema:
type: array
items:
type: string
```
Given the following JSON response:
```
{
"keys": ["one", "two", "three"]
}
```
The following properties would be made available in AppMap data:
```json …
```
> feat: Implement `items` Parameter object format (AppMap v1.10.0)

- lib/appmap/value_inspector.rb
We now expose the following:
- `APPMAP_PROPERTY_MAX_DEPTH`: The maximum depth a return value will be traversed when describing schema.
- `APPMAP_PROPERTY_MAX_ARRAY_ELEMENTS`: The maximum number of array elements that will be inspected when describing schema.
> feat: Allow environment configuration of property value inspection

- appmap.yml
- lib/appmap/minitest.rb
- test/fixtures/minitest_recorder/test/hello_failed_test.rb
- test/minitest_test.rb
AppMap `test_status` is not reporting `failed` when a Minitest fails. This is the fix for that.
> fix: Report minitest test status

- spec/schema_spec.rb
Show that generating the schema for nested Arrays ignores max_depth.
> test: add spec for nested Array schema generation

- lib/appmap/minitest.rb
- lib/appmap/rspec.rb
- lib/appmap/util.rb
- spec/util_spec.rb
- test/minitest_test.rb
- test/rspec_test.rb
`backtrace_locations` says:
> Returns any backtrace associated with the exception
So, I guess it may be nil.
Fixes #324
> fix: backtrace_locations may be nil

- lib/appmap/config.rb
- lib/appmap/hook/method.rb
- spec/method_hash_key_spec.rb
Encountered while mapping forem:
```
An error occurred while loading ./spec/models/reaction_category_spec.rb.
Failure/Error: end
TypeError:
no implicit conversion of Hash into Integer
WARNING: Shared example group 'Taggable' has been previously defined at:
/home/runner/work/forem/forem/spec/models/shared_examples/taggable_spec.rb:1
...and you are now defining it at:
/home/runner/work/forem/forem/spec/models/shared_examples/taggable_spec.rb:1
The new definition will overwrite the original one.
```
> fix: Handle KeyError in signature lookup

- lib/appmap/handler/rails/context.rb
- lib/appmap/handler/rails/request_handler.rb
- lib/appmap/railtie.rb
- spec/fixtures/rails7_users_app/Gemfile
- spec/fixtures/rails7_users_app/config/application.rb
- spec/fixtures/rails7_users_app/lib/hijacker.rb
- spec/fixtures/rails7_users_app/spec/system/rack_hijacking_spec.rb
- spec/rails_recording_spec.rb
- spec/rails_spec_helper.rb
Hook requests in Rails on the Rack level in addition to ActionController. This allows intercepting any changes and responses made by the middleware. We're still hooking ActionController, because controller tests don't use Rack, but the ActionController hook is skipped if the rack hook has been activated on the request.
Fixes #323 (I believe)
> Hook Rack in Rails

- exe/appmap-agent-config
- lib/appmap/command/agent_setup/config.rb
- test/agent_setup_config_test.rb
This command will be used during the AppMap manual install process to initialize an `appmap.yml`.
> feat: Add `appmap-agent-config` command to bootstrap appmap.yml

- lib/appmap/agent.rb
- lib/appmap/rspec.rb
- lib/appmap/rswag.rb
- lib/appmap/trace.rb
- lib/appmap/util.rb
- spec/fixtures/rails7_users_app/Gemfile
- spec/fixtures/rails7_users_app/spec/requests/users_spec.rb
- spec/fixtures/rails7_users_app/spec/swagger_helper.rb
- spec/rails_recording_spec.rb
RSwag does all its work in a `before` hook, which doesn't work well with AppMap.
Implement an RSwag-specific recorder, and disable RSpec recording for RSwag tests.
Fixes #335
> feat: Record rswag

- lib/appmap/value_inspector.rb
- spec/value_inspector_spec.rb
> fix: Guard access to the :size method

- .rubocop.yml
- .standard.yml
- .travis.yml
- appmap.gemspec
- lib/appmap/agent.rb
- lib/appmap/class_map.rb
- lib/appmap/config.rb
- lib/appmap/cucumber.rb
- lib/appmap/detect_enabled.rb
- lib/appmap/gem_hooks/activejob.yml
- lib/appmap/hook.rb
- lib/appmap/hook/method.rb
- lib/appmap/hook/method/ruby2.rb
- lib/appmap/hook/method/ruby3.rb
- lib/appmap/hook/record_around.rb
- lib/appmap/metadata.rb
- lib/appmap/middleware/remote_recording.rb
- lib/appmap/minitest.rb
- lib/appmap/rspec.rb
- lib/appmap/trace.rb
- lib/appmap/util.rb
- spec/around_recording_spec.rb
- spec/fixtures/hook/job.rb
- spec/fixtures/rails7_users_app/app/jobs/print_user_count_job.rb
- spec/fixtures/rails7_users_app/config/environments/development.rb
- spec/fixtures/rails7_users_app/config/environments/test.rb
- spec/fixtures/rails7_users_app/lib/tasks/count_users.rake
- spec/hook_spec.rb
- spec/remote_recording_spec.rb
- spec/request_recording_spec.rb
Methods labeled `job.perform`, `cli.command`, `message.handle` will automatically start and end a recording, if `APPMAP_RECORD_REQUESTS` is enabled.
Fixes https://github.com/getappmap/appmap-ruby/issues/345
> feat: Record "around" method

- lib/appmap/minitest.rb
- test/fixtures/minitest_recorder/Gemfile
- test/fixtures/minitest_recorder/test/hello_tagged_test.rb
- test/fixtures/minitest_recorder/test/test_helper.rb
- test/minitest_test.rb
Check to see if Minitest::Tagz has been used the add the tag :noappmap
to a test method. If so, don't generate an AppMap for the test.
Fixes #350 .
> Minitest tagz 20240130

- .travis.yml
- lib/appmap/handler/rails/request_handler.rb
It seems in some ancient Rails versions there are routes that don't define engine? method which we use to detect engines. Check if the method exists before using.
Note the affected versions are all end of life; the fix is simple but getting a test case would be more complicated so I skipped it.
Fixes #364
> fix: Handle rack apps without engine? method in Rails
